---
title: "Attrition App"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(shiny)
library(shinyjs)
library(ggplot2)
library(readr)

# URL to the raw content of the CSV file on GitHub
github_url <- "https://raw.githubusercontent.com/Weiprecht/Weiprecht.github.io/main/Attrition_app/CaseStudy2-FallData-updated.csv"

# Read the CSV file from the GitHub repository
attrition_Data <- read_csv(github_url)


# # UI part
ui <- fluidPage(
  titlePanel("Attrition Data Analysis"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("selected_variable", "Select Variable:",
                  choices = c("OverTime", "JobRole", "EnvironmentSatisfaction"),
                  selected = "OverTime")
    ),
    mainPanel(
      plotOutput("attrition_barplot")
    )
  )
)

# Server part
server <- function(input, output) {
  output$attrition_barplot <- renderPlot({
    attrition_Data %>%
      group_by(Attrition, !!sym(input$selected_variable)) %>%
      summarise(cnt = n()) %>%
      mutate(freq = (cnt / sum(cnt)) * 100) %>%
      ggplot(aes(x = !!sym(input$selected_variable), y = freq, fill = Attrition)) +
      geom_bar(position = position_stack(), stat = "identity", width = 0.7) +
      geom_text(aes(label = paste0(round(freq, 0), "%")),
                position = position_stack(vjust = 0.5), size = 3) +
      scale_y_continuous(labels = function(x) paste0(x, "%")) +
      labs(title = paste("Attrition and", input$selected_variable),
           x = input$selected_variable, y = "Percentage") +
      scale_fill_manual(values = c("red", "blue")) +
      theme(axis.text.x = element_text(angle = 20, hjust = 0.5))
  })
}
 

# Run the application
shinyApp(ui = ui, server = server)


```